### ISSUE TITLE
Current Online Player Names Metric

### ISSUE THREAD

**Issue by BlockyBlockling** [armsnyder/a2s-exporter#11]
Hey There,
I love your Project. My Problem is that I require another Metric to display the names/ids of the Players that are currently online.
I want to be able to cover the amount of different players online over a Time period.

For that, I require a metric like:
`a2s_player_names`

That shows the names of the currently online players, either in one value for each player or JSON string.

Would like to help with the implementation if this Project is still maintained.

**Comment by armsnyder** [comment]
Hi @BlockyBlockling. I'm glad you're loving the project. 😄 

I've added a new `player_info` metric for this purpose. The value is 1 and there is a `player_name` label. This has been released in [v0.4.0](https://github.com/armsnyder/a2s-exporter/releases/tag/v0.4.0).

You should be able to get the desired result of seeing each online player with the query `sum by(player_name) (a2s_player_info)`. 😉
