### ISSUE TITLE
Panic: runtime error: index out of range [3] with length 1

### ISSUE THREAD

**Issue by therileycloud** [armsnyder/a2s-exporter#7]
Installed on a few different machines, getting runtime errors while connecting to a rust server.
Didn't seem to have the issue initially but then the issue appeared after about 2h ish (as server pop rised).
A lower pop server runs no issue.

```
Serving metrics at http://127.0.0.1:9841/metrics

panic: runtime error: index out of range [3] with length 1
goroutine 6 [running]:
encoding/binary.littleEndian.Uint32(...)
        /usr/local/go/src/encoding/binary/binary.go:80
github.com/rumblefrog/go-a2s.(*PacketReader).ReadUint32(...)
        /go/pkg/mod/github.com/rumblefrog/go-a2s@v1.0.1/packet.go:89
github.com/rumblefrog/go-a2s.(*Client).parsePlayerInfo(0xc00017aa80, {0xc0001a0580?, 0x9?, 0x9?})
        /go/pkg/mod/github.com/rumblefrog/go-a2s@v1.0.1/player.go:133 +0x4af
github.com/rumblefrog/go-a2s.(*Client).QueryPlayer(0x7ffc68301f73?)
        /go/pkg/mod/github.com/rumblefrog/go-a2s@v1.0.1/player.go:95 +0x138
github.com/armsnyder/a2s-exporter/internal/collector.(*Collector).queryInfo(0xc0000c0860)
        /build/internal/collector/collector.go:128 +0x2a5
github.com/armsnyder/a2s-exporter/internal/collector.(*Collector).Collect(0xc0000c0860, 0xc000060120)
        /build/internal/collector/collector.go:68 +0x2d
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:467 +0x55d
```

**Comment by armsnyder** [comment]
Hi @therileycloud!

Thanks for your report. I read through the [code that parses player data](https://github.com/rumblefrog/go-a2s/blob/ee5866fe7795a16e88fb230474fde5289215d273/player.go#L109), and it looks to be following the [a2s binary protocol](https://developer.valvesoftware.com/wiki/Server_queries#A2S_PLAYER) correctly.

All I can definitively determine from the panic is that the player data was in an unexpected format, so any more information you could provide about the number or nature of players would help.

The panic seems to occur right after reading a variable-length string for the player's name. Do you happen to know the username for the player who joined right before it crashed? Is there anything different about this username, like being particularly long or containing whitespace characters?

**Comment by therileycloud** [comment]
I wish I could answer that but we have about 250 active players, people hopping on & off. It went off at about 90 players ish. People connecting from everywhere with every type of character from emoji to Chinese character.

However, this can probably help but since a few years ago, Rust doesn't actually communicate the user names through the A2S protocol (to prevent stream sniping, offline raiding, etc). And provides random "regular" names with regular characters such as "susan", "simon", etc. So should be absolutely no weird characters for player names :)

**Comment by armsnyder** [comment]
Hrmm, maybe they're omitting a null-terminator character on one of their "regular" names? That would certainly cause this panic. Seems unlikely though. I opened a [support ticket](https://support.facepunchstudios.com/hc/en-us/requests/264627) asking if they made any alterations to the A2S_PLAYER response and will see what they say.

**Comment by armsnyder** [comment]
90 players happens to be right around the amount of data that would overflow the default packet size, so that is suspicious.

**Comment by armsnyder** [comment]
Could you try the [latest release](https://github.com/armsnyder/a2s-exporter/releases/tag/v0.2.0) and configure the max packet size to `2800`, which is double the default?

**Comment by therileycloud** [comment]
Unfortunately the server characteristics change pretty often, so currently at about 65-70 pop so somewhat lower.

I tried running the older version and it no longer panics, however it doesn't serve metrics with the following error :

```
An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric "a2s_player_duration" { label:<name:"player_index" value:"0" > label:<name:"player_name" value:"kris" > label:<name:"server_name" value:"The Beehive - Solo/Duo - Fullwiped 09/12" > gauge:<value:2380.327880859375 > } was collected before with the same name and label values
* collected metric "a2s_player_score" { label:<name:"player_index" value:"0" > label:<name:"player_name" value:"kris" > label:<name:"server_name" value:"The Beehive - Solo/Duo - Fullwiped 09/12" > gauge:<value:0 > } was collected before with the same name and label values
```
_Note : there was some variability in the exact code, it was the "gauge:<value:2380.327880859375 >" bit where the number would change._

The same error seemed to be **initially** displayed on the latest version, but it is now all is working. Hopefully tomorrow the pop should reach > 90 so I'll be able to update you on this. Thanks a ton!

**Comment by armsnyder** [comment]
> This is a fixed list of a few thousand names and there are quite possibly duplicate names connected on to the same server, even though this is a rare occurrence. Could this be the issue ?

Yes this would definitely cause it. Nice find!

> Would there be a way to deactivate all of the player commands?

I was starting to think the same thing...

I just released [v0.3.0](https://github.com/armsnyder/a2s-exporter/releases/tag/v0.3.0) which fixes the duplicate player name bug and also adds an argument to exclude player metrics.

**Comment by armsnyder** [comment]
No problem, and thanks for following though with running some tests! 🙏 I look forward to what you find. For this one - `latest with player data to test your fix` - did you increase max packet size?

**Comment by therileycloud** [comment]
Yes the latest with player data to test your fix includes the `A2S_EXPORTER_MAX_PACKET_SIZE `set to 2800.
